SELECT PRODUCT_CODE, SUM(PRICE*OFFLINE_SALE.SALES_SUM) AS SALES
FROM PRODUCT
INNER JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_SUM
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID) AS OFFLINE_SALE ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC
;
