SELECT     CASE
        WHEN HOUR(DATETIME) = 9 THEN 9
        WHEN HOUR(DATETIME) = 10 THEN 10
        WHEN HOUR(DATETIME) = 11 THEN 11
        WHEN HOUR(DATETIME) = 12 THEN 12
        WHEN HOUR(DATETIME) = 13 THEN 13
        WHEN HOUR(DATETIME) = 14 THEN 14
        WHEN HOUR(DATETIME) = 15 THEN 15
        WHEN HOUR(DATETIME) = 16 THEN 16
        WHEN HOUR(DATETIME) = 17 THEN 17
        WHEN HOUR(DATETIME) = 18 THEN 18
        WHEN HOUR(DATETIME) = 19 THEN 19
    END AS HOUR, COUNT(ANIMAL_ID) AS 'COUNT'
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >=9 AND HOUR(DATETIME) <=19
GROUP BY 
    CASE
        WHEN HOUR(DATETIME) = 9 THEN 9
        WHEN HOUR(DATETIME) = 10 THEN 10
        WHEN HOUR(DATETIME) = 11 THEN 11
        WHEN HOUR(DATETIME) = 12 THEN 12
        WHEN HOUR(DATETIME) = 13 THEN 13
        WHEN HOUR(DATETIME) = 14 THEN 14
        WHEN HOUR(DATETIME) = 15 THEN 15
        WHEN HOUR(DATETIME) = 16 THEN 16
        WHEN HOUR(DATETIME) = 17 THEN 17
        WHEN HOUR(DATETIME) = 18 THEN 18
        WHEN HOUR(DATETIME) = 19 THEN 19
    END
ORDER BY HOUR ASC
;