# SELECT CATEGORY, PRICE, MAX_PRICE_TABLE.PRODUCT_NAME
# FROM FOOD_PRODUCT
# INNER JOIN (
#     SELECT MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
#     FROM FOOD_PRODUCT
#     WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
#     GROUP BY CATEGORY) AS MAX_PRICE_TABLE
# ON FOOD_PRODUCT.PRODUCT_NAME = MAX_PRICE_TABLE.PRODUCT_NAME
# GROUP BY CATEGORY

# ORDER BY MAX(PRICE) DESC
# ;


SELECT FOOD_PRODUCT.CATEGORY, FOOD_PRODUCT.PRICE, FOOD_PRODUCT.PRODUCT_NAME
FROM FOOD_PRODUCT
INNER JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ("과자", "국", "김치", "식용유") 
    GROUP BY CATEGORY) AS MAX_PRICE
    ON FOOD_PRODUCT.CATEGORY = MAX_PRICE.CATEGORY AND FOOD_PRODUCT.PRICE = MAX_PRICE.MAX_PRICE
ORDER BY PRICE DESC
;

